[package]
name = "senoru"
version = "0.1.0"
authors = ["Jason Reilly <jdr0887@gmail.com>"]
edition = "2018"
keywords = ["password", "manager", "secure", "notepad"]

[dependencies]
base64 = ">=0.12.3"
chrono = { version = ">=0.4.13", features = ["serde"]} 
diesel = { version = ">=1.4.5", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = ">=1.4.0"
dirs = ">=3.0.1" 
gdk = ">=0.13.0"
gtk = { version = ">=0.9.2", features = ["v3_24"] }
gio = { version = ">=0.9.0", features = ["v2_44"] }
glib = ">=0.10.0"
lazy_static = ">=1.4.0"
log = { version = ">=0.4.8", features = ["std"] }
magic-crypt = ">=3.1.3"
passwords = ">=3.1.2"
r2d2 = ">=0.8.9"
simple_logger = ">=1.6.0"
serde = ">=1.0.114"
serde_derive = ">=1.0.114"
serde_json = ">=1.0.56"
structopt = ">=0.3.15"
uuid =  { version = ">=0.8.1", features = ["serde", "v4"]}
