[package]
name = "senoru"
version = "0.1.0"
authors = ["Jason Reilly <jdr0887@gmail.com>"]
edition = "2018"

[dependencies]
bincode = ">=1.3.1"
chrono = { version = ">=0.4.11", features = ["serde"]} 
diesel = { version = ">=1.4.5", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = ">=1.4.0"
dirs = ">=3.0.0"
gtk = { version = "0.8.1", features = ["v3_20"] }
gio = { version = "0.8.1", features = ["v2_44"] }
glib = ">=0.9.3"
glib-sys = ">=0.9.1"
humantime = ">=2.0.1"
itertools = ">=0.9.0"
lazy_static = ">=1.4.0"
log = { version = ">=0.4.8", features = ["std"] }
magic-crypt = ">=3.1.2"
num_cpus = ">=1.13.0"
r2d2 = ">=0.8.8"
rand = ">=0.7.3"
rand_distr = ">=0.2.2"
rayon = ">=1.3.1"
regex = ">=1.3.9"
ring = ">=0.17.0-alpha.2"
simple_logger = ">=1.6.0"
serde = ">=1.0.114"
serde_derive = ">=1.0.114"
serde_json = ">=1.0.55"
structopt = ">=0.3.15"
strum = ">=0.18.0"
strum_macros = ">=0.18.0"
uuid =  { version = ">=0.8.1", features = ["serde", "v4"]}
